on:
  push:
    branches:
      - main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release

      # Renv actions, first get R up and running
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2

      - name: Render Quarto file
      - uses: quarto-dev/quarto-actions/publish@v2
        with:
          path: template.qmd
          target: gh-pages
